# Generated by Django 5.1.1 on 2024-09-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categoria',
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.categoriaservico')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('sucesso', 'Concluído com sucesso'), ('falha', 'Concluído sem sucesso')], max_length=20)),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.contratado')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.contratante')),
                ('servicos_contratados', models.ManyToManyField(to='administrativo.tiposervico')),
            ],
        ),
        migrations.AddField(
            model_name='contratado',
            name='tipos_servicos',
            field=models.ManyToManyField(to='administrativo.tiposervico'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
